# Generated by Django 3.0.8 on 2020-08-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('gov', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('year', models.IntegerField()),
                ('kilos', models.CharField(max_length=200)),
                ('pay_type', models.CharField(max_length=200)),
                ('transmission', models.CharField(max_length=200)),
                ('cc', models.IntegerField()),
                ('chasis', models.CharField(max_length=200)),
                ('features', models.CharField(max_length=500)),
                ('color', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('url', models.URLField()),
            ],
        ),
    ]
