# Generated by Django 3.0.8 on 2020-08-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='date',
            field=models.CharField(max_length=200),
        ),
    ]
