# Generated by Django 3.0.8 on 2020-08-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0002_auto_20200816_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='cc',
            field=models.CharField(max_length=200),
        ),
    ]
