# Generated by Django 3.0.8 on 2020-08-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0003_auto_20200816_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='date',
            field=models.DateField(),
        ),
    ]
