# Generated by Django 3.0.8 on 2020-09-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0006_auto_20200817_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='imgs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
