# Generated by Django 3.0.8 on 2020-10-17 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0008_auto_20200916_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='ad',
            name='cc',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='chasis',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='city',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='color',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='features',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='gov',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='imgs',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='kilos',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='pay_type',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='transmission',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='url',
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curator.Brand')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curator.Year')),
            ],
        ),
        migrations.AlterField(
            model_name='ad',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curator.Brand'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curator.Model'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curator.Year'),
        ),
    ]
