# Generated by Django 3.0.8 on 2020-10-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0009_auto_20201017_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='year',
            field=models.ManyToManyField(to='curator.Year'),
        ),
        migrations.RemoveField(
            model_name='model',
            name='year',
        ),
        migrations.AddField(
            model_name='model',
            name='year',
            field=models.ManyToManyField(to='curator.Year'),
        ),
    ]
