# Generated by Django 3.0.8 on 2020-10-23 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0010_auto_20201017_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='year',
        ),
        migrations.RemoveField(
            model_name='model',
            name='year',
        ),
    ]
